<div class="post-title">
    {% if not is_index %}
        <div style="text-align:center;color: #ccc;font-size:22px;">
        -------------本文结束<i class="fa fa-paw"></i>感谢您的阅读-------------<br>
        本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" >知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可。
         <p>有问题可以跟我发邮件哦,记得填写自己可用的邮件地址哦: <a href="http://www.caoayu.xyz:3001">点我发送邮件<a/><p/>
        </div>
    {% endif %}
   
    
</div>